import type { PrismaClient } from '@prisma/client';

export type DatabaseClient = Pick<
  PrismaClient,
  | 'repProfile'
  | 'repSignatureProfile'
  | 'repSocialLink'
  | 'landingPage'
  | 'lead'
  | 'leadNote'
  | 'activityLog'
  | 'user'
  | 'connectedAccount'
  | 'emailMailbox'
  | 'emailThread'
  | 'emailMessage'
  | 'calendarEvent'
  | 'meeting'
  | 'meetingArtifact'
  | 'meetingParticipant'
  | 'callSummary'
  | 'actionItem'
  | 'emailDraft'
  | 'notionSyncRecord'
  | 'externalProfileSource'
  | 'linkedInProfileLink'
  | 'employmentSnapshot'
  | 'employmentChangeEvent'
  | 'profileMatchCandidate'
  | 'relationshipHistory'
  | 'championFlag'
  | 'contactWatchlist'
  | 'careerMovementAlert'
  | 'relationshipMilestone'
  | 'contactCompanyAssociation'
  | 'expansionOpportunitySignal'
  | 'repActionPrompt'
  | 'relationshipEdge'
  | 'account'
  | 'accountContact'
  | 'opportunity'
  | 'outreachDraft'
  | 'draftGenerationContext'
  | 'priorityScore'
  | 'priorityReason'
  | 'repTaskSuggestion'
  | '$transaction'
>;
